### ISSUE TITLE
Single Board Computers

### ISSUE THREAD

**Issue by faddat** [universelabs/universe#15]
**Single Board Computers**
This is a list of single board computers that it makes sense to try out.  Once we've got a hardware platform we feel comfortable with, the next step is to create an image builder so that we can do a build that works like:

board os -> Universe software -> .img file for immediate testing

This way, we can make changes to software and rapidly test them running on our chosen hardware.  

**Devices**
- [x] Raspberry Pi 3B+
- [x] Pine Rock64 4GB LTS
- [x] Pine A64+
- [x] Pine A64 LTS
- [x] SiFive HiFive
- [x] Orange Pi PC

| Device  | Pirce  | Processor  | RAM  | Wifi  |
|---|---|---|---|---|
| Raspberry Pi 3B+  | $35  | 4-core-arm (Brodacom)  | 1GB  | Yes   |
| Pine Rock64  | $45  | 4-Core-Arm64 (Rockchip)   | 4GB  | No  |
| Pine A64+  | $29  | 4-core-arm64 (allwinner)  | 2GB  |  No |
| Pine A64 LTS  | $32  | 4-core-arm (allwinner)  | 2GB  | Yes   |
| SiFive HiFive  | $1000  | 4-core-RISC-V   | 1GB  | No  |
| Orange PI PC  | $15  | 4-core-armv7h (allwinner)  | 1GB  |  No |

**Comment by guylepage3** [comment]
@faddat want to provide a price for each of the computers?

**Comment by faddat** [comment]
I'll add a table to the issue, with price and some other factors.

**Comment by guylepage3** [comment]
Closing this issue for now. If we do more hardware we can create a new issue.
