### ISSUE TITLE
Weekly Scrum Call - July 22, 2019

### ISSUE THREAD

**Issue by faddat** [universelabs/universe#21]
**Description**
Weekly Scrum Call
Jul 22, 2019
Attendees:  @modkaffes @faddat @itamarreif @guylepage3

**Minutes**
- Guy updated team on seed round funding.
- Discussed the current state of the deck.
- Blog: We want to self-host our blog
  - @modkaffes to research Gatsby to see if it has good SEO support. If it does not, then we will have to go with Ghost.
  - Guy has roughly 20 posts ready to go.
  - First post should be on "Why what we're doing is so important."
- We will be extending our current sprint by one week.
  - Main goals for this week.
    - @faddat @itamarreif Finalize stack for Feather.
    - @guylepage3 @modkaffes Design and build out new on-boarding views for webapp.
    - @modkaffes Finalize research on blog platform.
- @guylepage3  to clean up sprint kanban board.
- @guylepage3 to present team with new Roadmap.
- Discussion around website update. Not to be updated.
- Next sprint
  - Get feather working (Repo: https://github.com/universelabs/universe-mobile)
  - Daily front end updates
- Jake to go through readmes and create a readme issue.  To use @guylepage3's readme template. 
* @guylepage3 to post one-paragraph project explainer from investor intro e-mails in an issue in the same spot as our deck issue.

Here comes a great week!

**Comment by guylepage3** [comment]
Great notes @faddat. Thank you sir.
