### ISSUE TITLE
Engineering Call - Jul 24

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe#22]
### Engineering Call 
Date: Wed, Jul 24, 2019 10am.
Attendees: @itamarreif @faddat @modkaffes @guylepage3 

### Minutes from Call
- @faddat got the Feather mobile device talking to devices.
- Went over the Universe Flow Illustration / Diagram from [#23 Proposal: Update to path to obfuscation and beyond...](https://github.com/universelabs/universe/issues/23)
- Determined goals and deliverables for next few weeks to **have the web app interacting with a running mobile/feather device in a client-server relationship**. There are two portions to accomplish this during [Sprint 5 (Current sprint)](https://github.com/orgs/universelabs/projects/6) and [Sprint 6](https://github.com/orgs/universelabs/projects/7);
  - 1a. Build BLE (Bluetooth Low Energy) server with CRUD capability. @itamarreif @faddat 
  - 2a. Build Web Client to interact with Feather device. @modkaffes @guylepage3 
  - 2b. Build out crypto infrastructure running on Feather device. @itamarreif @faddat 
- Discussed mobile deployment.
  - @guylepage3 to setup call with @itsprof and get his take on the mobile side of things.

### Goals
- Have the web app interacting with a running mobile/feather device in a client-server relationship by the end of [Sprint 6](https://github.com/orgs/universelabs/projects/7).

**A few useful resources discussed**:

- The official Espressif ESP32 documentation: https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html
- React Native BLE library: https://github.com/Polidea/react-native-ble-plx
- A primer on the security infrastructure built into the ESP32 chips: https://medium.com/the-esp-journal/understanding-esp32s-security-features-14483e465724
- More docs about the Flash Encryption feature: https://docs.espressif.com/projects/esp-idf/en/latest/security/flash-encryption.html

Please comment with any more relevant links and ideas!

**Comment by guylepage3** [comment]
@itamarreif I just updated your notes slightly.

**Comment by guylepage3** [comment]
Closiing
