### ISSUE TITLE
Interesting resources regarding DApps

### ISSUE THREAD

**Issue by modkaffes** [universelabs/universe#3]
This is a place to collect and discuss interesting resources from the community which address issues tightly or loosely related to dApp development, lifecycle and usage.

### Key/identity management

[Authentiq](https://www.authentiq.com/)
> With [the] mobile app, Authentiq ID, you can create a verified ID on your phone and use this to sign in safely with just a touch. No personal data is stored in centrally, it's only exchanged with your consent, and cryptographic keys never leave your phone. ([source](https://cards.producthunt.com/cards/comments/472427?v=1))

**Comment by guylepage3** [comment]
This is great @modkaffes..

I would also like to add...
- Casa – https://keys.casa/
    - [Bitcoin Thieves Beware: Super Secure Wallet Maker Casa Raises $2 Million](https://www.forbes.com/sites/jeffkauflin/2018/03/02/bitcoin-thieves-beware-super-secure-wallet-maker-casa-raises-2-million/#249a24cb4423)

**Comment by guylepage3** [comment]
There seems to be a lot of players taking different approaches to this problem. Our approach is a simple approach. Also, it is one where our focus is to "grow" crypto. In fact, we would love to integrate with folks like Authentiq. 

Would love to add them to our on-boarding process for sure. We are an open source community and our #1 mission is to advance crypto UX in anyway possible. We will never say no to anyone requesting integration.

**Comment by guylepage3** [comment]
Closing
