### ISSUE TITLE
Look into Mailchimp Slack app preferences

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#33]
**Description**
Look into Mailchimp Slack app preferences.

@dantrevino mentioned the following in Slack.

Dan 11:38 PM
@guy i'm not sure putting peoples email in public #social channel via mailchimp is a good idea.  Is there an opt-in for doing that?

As a result we should look into finding a solution that does not expose subscriber's email address.

**Comment by guylepage3** [comment]
Hm.. So my thoughts on this is that, if someone has a problem with their email showing, which most people’s email address is public anyway, then they can let us know and we'll remove it. 

Or if a community member mentions the same thing, we will remove the integration.

But as for now. Not a single subscriber has commented on this.

Let's keep an eye out for community members not wanting their email to be shown.

**Comment by guylepage3** [comment]
Closing this issue for now. Will revisit if when it becomes an issue with a community member.

**Comment by dantrevino** [comment]
Some people could be registering with work or non-public emails.  Does Ryan Shae, who's not in our slack, understand his email was shared publicly?  I would bet that none of the subscribers know about it.  Unless we're making it explicit during the newsletter signup, this is just plain wrong.  If we're asking people to trust us with their keys, and we can't even keep their newsletter requests private, why should they trust us?  Do we send out the newsletter with everyone's email in the "To" field?  Why not?

I strongly disagree with this decision.

**Comment by guylepage3** [comment]
@dantrevino can you find us an alternative way to execute this?

**Comment by dantrevino** [comment]
I'm not sure what the goal is.  I suggest removing mailchimp integration.  I do not understand why that is necessary or valuable.

**Comment by guylepage3** [comment]
Pushing to Sprint 7.

**Comment by vsund** [comment]
Couldn't we just remove the Slack integration of Mailchimp? Or alternatively just move it to a private channel?

**Comment by guylepage3** [comment]
Yep. I adjusted the integration yesterday. Forgot to close this issue.
