### ISSUE TITLE
Versioning and releases

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#35]
**Description**
We should choose a process for versioning and releases that allows us to easily deploy while being responsible with our software releases.

**Versioning Reference(s)**
- [Git Flow AVH (Git extension) Documentation](https://github.com/petervanderdoes/gitflow-avh/wiki)
- [Git Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
- [semantic-release (recommended by GitHub)](https://github.com/semantic-release/semantic-release)
- [Semantic versioning 2.0.0](https://semver.org)

**Release Reference(s)**
- [Example: Create React App Releases](https://github.com/facebook/create-react-app/releases)
- [Git Flow Cheatsheet Releases](https://danielkummer.github.io/git-flow-cheatsheet/)

**Deliverables**
- Guy to update `README.md` files to pull from `Git Tags`.
  - [Shields.io Version Badges](https://shields.io/category/version)
- Team needs to push releases where necessary. alpha, beta, etc. releases where applicable.

**Comment by itamarreif** [comment]
https://www.fredonism.com/a-practical-take-on-gitflow-and-semantic-versioning relevant blog post

**Comment by guylepage3** [comment]
So this is what I am proposing for v1 on this. We can slowly get feedback from the community as we go.

**Universe Semantic Versioning**
`v0.1.0-alpha`
`v0.1.4-alpha`
`v0.2.22-alpha`
`v0.4.0-beta`
`v0.5.13-beta`
`v1.0.0`
`v1.14.3`
`v3.2.78`
etc..

We use git tags to declare versions and manually create releases for the time being. We use `git flow` only for branching.

**Comment by guylepage3** [comment]
Closing issue
