### ISSUE TITLE
Decentralized peer-to-peer network, Phase 3 roadmap

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe#38]
**Description**
This is a rough mock of our plans to expand Universe's key recovery service. The recovery service would augment the currently planned Core+API+KeyManager architecture, most likely by adding recovery endpoints to Core.

**Network**
Using a decentralized peer-to-peer network, keys would be split and distributed among the participants, likely in a threshold-based construction. Retrieval from the network would require the user to provide an authorization token obtained from the KYC process. 

Important issues that need to be addressed are arbitrary key storage, figuring out the KYC process, and the degree of decentralization we wish to allow. It would be interesting to allow users to chose their KYC provider out of a set of network-supported providers, allowing for different security models, varying "depths" of KYC, etc.

**Experience**
The main goal is to achieve the recoverability offered by BIP32-esque constructions that use a mnemonic while providing the user a much more "human-readable" experience. Intuitively, this allows users to recover their cryptographic keys using their tangible, real-world identity, rather than an arcane mathematical process. The identity verification process is already one that consumers are familiar with and are willing to accept at the event that they lose access to their bank or credit card. 

Additionally, part of Universe's experience would offer a streamlining of the KYC process meaning that KYC information would already be provided once during the users' onboarding process.

**Comment by guylepage3** [comment]
Really great work here @itamarreif!
