### ISSUE TITLE
Roadmap: Specs discussion

### ISSUE THREAD

**Issue by arisgk** [universelabs/universe#4]
Based upon the feedback for the community, dapp developers, and platform founders, Phase 1 focus is key management software. Phase 2 we will be moving over to hardware device for key management. Universe targets onboarding dApp users with one setup for all major platforms. 

- For v1, we will focus on managing users' “less secure” private keys and most importantly sign up on the top 5-10 services all at one time
    - Less secure would mean, social app identity
    - More secure (something we’ll do later) - identity key management for serious apps that manage your health data, government id, etc.
- We want 1 single place to go for our MetaMask, Blockstack, DID, Solid, U-port, Civic, etc. identities and phrases, keys, or whatever else people are calling crypto passwords backups.
- We want a password because passwords work.
- We will need to pay attention to how each platform signs up its users, then sign them up on each platform and then encrypt and store their backup phrases.
- Universe is a fail-safe place for users to go when they forget their back up phrases.
- Despite we want to use a shared decentralized identity standard like the one developed at [Decentralized Identity Foundation](https://identity.foundation/), we want to figure out an alternative way if things are moving slowly with the standard.

**Comment by guylepage3** [comment]
@arisgk this is spot on. I think we now need to start pulling in dapp developers to confirm that our findings are correct and that we're not missing anything. But I think you've nailed. it here. Great job!

**Comment by arisgk** [comment]
@guylepage3 I think we should add a spec
- We don't want to use a centralized server / data store

**Comment by faddat** [comment]
"Universe is a fail-safe place for users to go when they forget their back up phrases."

I like it.  

How will we make it work?

**Comment by guylepage3** [comment]
Backlogging.

**Comment by guylepage3** [comment]
Closing issue
