### ISSUE TITLE
Remove newsletter email addresses from #social channel

### ISSUE THREAD

**Issue by vsund** [universelabs/universe#40]
**Description**
The Mailchimp integration in the (public) #social channel in Slack posted the subscribing email addresses. Although it's fixed now (https://github.com/universelabs/universe/issues/33), there are still the old messages containing email addresses in there.

**Tasks**
- [ ] Remove every message by hand or find a way to remove all messages of the Mailchimp integration at once

**Comment by guylepage3** [comment]
Hey @vsund can we get you to do this? Let me know and I'll add you as a Slack admin. Thx.

**Comment by vsund** [comment]
Sure, but probably not before the 9th :)

**Comment by guylepage3** [comment]
Sounds good sir. Just let me know when you're ready and I'll provide credentials. 👍

**Comment by vsund** [comment]
Seems like it's not possible to bulk remove messages anymore (thanks Slack :D). But since the bigger part of the message history it behind the 10000 message limit, there only were 11 messages containing subscriptions (5th June to 9th September).

Just removed those, though need to keep in mind that _there are probably more_ behind Slack's message limit.

**Comment by guylepage3** [comment]
Thank you @vsund 👍
