### ISSUE TITLE
Understand how to run node.js apps on VM's

### ISSUE THREAD

**Issue by faddat** [universelabs/universe#56]
**Description**
Need to understand how to run node.js (Node, Express, Create-React-App) apps on virtual machine servers using NGINX.

**Tutorial list**
1. [Deploying a Node App to Digital Ocean (scotch.io)](https://scotch.io/tutorials/deploying-a-node-app-to-digital-ocean)
1. [How To Set Up a Node.js Application for Production on Ubuntu 18.04 (from DigitalOcean)](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04)
1. [Start to Finish: Deploying a React App on DigitalOcean](https://github.com/universelabs/universe/issues/56#issuecomment-541797347)
1. [Deploy React.js (create-react-app) Node.js to DigitalOcean Cloud](https://github.com/universelabs/universe/issues/56#issuecomment-541780009)
1. [Simplest Way to Deploy ReactJS Web App to Digital Ocean as Production](https://github.com/universelabs/universe/issues/56#issuecomment-541873295)
1. [Static React app in 20 mins with DigitalOcean](https://blog.logicalicy.com/static-react-app-in-20-mins-610662f47376).
1. [Deploy a Create-React-App Website to DigitalOcean](https://coderrocketfuel.com/article/deploy-a-create-react-app-website-to-digitalocean).

**Other for later**
- [Independent Deployment of the Frontend with Docker and Kubernetes](https://github.com/universelabs/universe/issues/56#issuecomment-541803512)

**Old references (DO NOT WATCH OR READ!)**
- [Full Node.js Deployment - NGINX, SSL With Lets Encrypt (Traversy Media YouTube)](https://github.com/universelabs/universe/issues/56#issuecomment-541799947)
- [How to get "create-react-app" to work with your API](https://github.com/universelabs/universe/issues/56#issuecomment-541808002)
- [Deploying a React-Node-MongoDB app to Google Cloud Platform’s Google App Engine](https://github.com/universelabs/universe/issues/56#issuecomment-541808084)

**Comment by guylepage3** [comment]
Slack reference https://universelabs.slack.com/archives/CD22EAGUX/p1570018426019900

**Guy Lepage** Oct 2nd at 8:13 AM

good morning @jacob

so here’s how you use nginx to run multiple ports on one GCP Compute Engine or Digital Ocean Droplet.

https://hackernoon.com/deploy-react-js-create-react-app-node-js-to-digitalocean-cloud-hosting-72206310017b

```
Let me explain to you very simple why we do use Nginx for this Nodejs Web application. Example: Our Chat app when we start it running on port 3000 that is default of Nodejs application running. we can change the port to 3001 or 3002, or 8080 … so if you pointed your domain tabvn.com to Degital Ocean cloud vps so this case we can visit the chat app in http://tabvn.com:3000 so we need just see nodejs web app in default port 80 such at http://tabvn.com , that is why we use Nginx.
```

So we do not need to remove the express server from universe.engineering

**Comment by guylepage3** [comment]
brb.. dog walk.. :)

**Comment by guylepage3** [comment]
[Start to Finish: Deploying a React App on DigitalOcean](https://hackernoon.com/start-to-finish-deploying-a-react-app-on-digitalocean-bcfae9e6d01b)

**Comment by guylepage3** [comment]
This is an old tutorial. Just posting for reference. I'm not suggesting this is one for us to execute. See "[Tutorial list](https://github.com/universelabs/universe/issues/56)" at top of issue for list to execute.
- [Full Node.js Deployment - NGINX, SSL With Lets Encrypt (Traversy Media YouTube)](https://www.youtube.com/watch?v=oykl1Ih9pMg&feature=youtu.be)

**Comment by guylepage3** [comment]
This is an old tutorial. Just posting for reference. I'm not suggesting this is one for us to execute. See "[Tutorial list](https://github.com/universelabs/universe/issues/56)" at top of issue for list to execute.
- [Independent Deployment of the Frontend with Docker and Kubernetes](https://www.youtube.com/watch?v=Td7w0_nD5_4)

**Comment by guylepage3** [comment]
This tutorial was something @itmarreif posted in Slack in late September.

@faddat, let’s both, you and I, run through this video today as well.

- [Independent Deployment of the Frontend with Docker and Kubernetes](https://www.youtube.com/watch?v=Td7w0_nD5_4)

**Comment by guylepage3** [comment]
This is an old tutorial. Just posting for reference. I'm not suggesting this is one for us to execute. See "[Tutorial list](https://github.com/universelabs/universe/issues/56)" at top of issue for list to execute.
- [How to get "create-react-app" to work with your API](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/)

**Comment by guylepage3** [comment]
This is an old tutorial. Just posting for reference. I'm not suggesting this is one for us to execute. See "[Tutorial list](https://github.com/universelabs/universe/issues/56)" at top of issue for list to execute.
- [Deploying a React-Node-MongoDB app to Google Cloud Platform’s Google App Engine](https://medium.com/@paulrohan/deploying-a-react-node-mongodb-app-to-google-cloud-platforms-google-app-engine-1ba680447d59)

**Comment by faddat** [comment]
@guylepage3 I do not think the one you mentioned as showing how to do multiple ports.... does multiple ports.

**Comment by guylepage3** [comment]
Can you provide context? @faddat

**Comment by guylepage3** [comment]
Did you complete the **tutorial 1** in it's entirety @faddat?

**Comment by guylepage3** [comment]
[Simplest Way to Deploy ReactJS Web App to Digital Ocean as Production](https://medium.com/@mixpeal/simplest-way-to-deploy-reactjs-web-app-to-digital-ocean-to-production-adfb9f1667ed)

**Comment by guylepage3** [comment]
@faddat Once all items in [#80 Digital Ocean migration – Critical Path](https://github.com/universelabs/universe.engineering/issues/80) are complete, write up findings and then close this issue. Thx.

**Comment by guylepage3** [comment]
Now that we're running micro-services this issue is moot. closing.

**Comment by faddat** [comment]
# Tutorial 1

* Very basic app with no routes.  If we changed our app to work like this one, our app would work.  
* Includes a bug, does not instruct user to install npm / node


Output:
```
tutorial1@tutorial1:~$ curl localhost:3000
Hey, I'm a Node.js app!tutorial1@tutorial1:~$ 
```

Tutorial 1 result:

Serving insecurely on port 80

See it here: http://142.93.6.162/

**Comment by faddat** [comment]
# Tutorial 2 - DIgital Ocean

This tutorial is out of date and not highly relevant:

* Node 6.x
* Ubuntu 16.04
* No express

I'll approximate as best I can with 18.04 and the latest stable node (not npm install node).  I'll reserve tutorial2.universe.engineering as DNS for this.

**Comment by guylepage3** [comment]
Here's a great visual for **Web Server (NGINX)** vs. **App Server (Node.js/Express.js)**

https://medium.com/dev-blogs/multiple-nodejs-apps-on-single-server-47b8bba3ec68

![image](https://user-images.githubusercontent.com/1711854/67693279-d61a8f00-f977-11e9-825d-6777def6d5f4.png)

**Comment by faddat** [comment]
Article is dokku propaganda and details routing subdomains to containers automatically with dokku.

**Comment by guylepage3** [comment]
Was not referencing the article. Was just showing the "visual" so that you can understand how NGINX fits in with everything.
